server:
  port: 8082

spring:
  application:
    name: user-service
    bad_request: 400
    conflict: 409
    success: 200
    not_found: 404

  datasource:
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

app:
  config:
    keycloak:
      server-url: http://localhost:8571
      realm: banking-service
      client-id: 24985208223-nm8j7d2bk6crhj5i1bibof4e9hr6qplv.apps.googleusercontent.com
      client-secret: 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

# Enable H2 console access (optional)
spring.h2.console.enabled: true
spring.h2.console.path: /h2-console
