spring:
  application:
    name: sequence-generator

  datasource:
    url: jdbc:h2:mem:sequence_generator;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

server:
  port: 8083

spring.h2.console.enabled: true
spring.h2.console.path: /h2-console
